name: earyzhe_webview_plugin_example
description: Demonstrates how to use the earyzhe_webview_plugin plugin.

dependencies:
  flutter:
    sdk: flutter
  earyzhe_webview_plugin:
    path: ../

flutter:
  uses-material-design: true
